version: '3.7'
services:
  test-qgis-server:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - qgis-server
  qgis-server:
    image: ${CONTAINER_IMAGE:-sogis/oereb-wms:2}
    environment:
      QGIS_SERVER_PARALLEL_RENDERING: "true"
      QGIS_SERVER_MAX_THREADS: 2
      QGIS_FCGI_MAX_PROCESSES: 2
      QGIS_FCGI_MIN_PROCESSES: 1
      QGIS_SERVER_LOG_LEVEL: 0
    ports:
      - 8083:80
    depends_on:
      - db
  db:
    image: sogis/oereb-db:2
    environment:
      POSTGRES_DB: oereb
      POSTGRES_PASSWORD: mysecretpassword
      PG_READ_PWD: dmluser
      PG_WRITE_PWD: ddluser
      GRETL_PG_WRITE_PWD: gretl
    ports:
      - 54323:5432